"""Turn pytest JUnit XML into the results tables on the `Numerical tests` docs page.

The page claims the port is asserted against upstream at every layer. Writing that claim by hand
means it is true on the day it is written and unverified every day after, so the tables are
generated from an actual run instead: statuses and xfail reasons come from the JUnit XML, and each
test's description is its own docstring, read from the source with `ast`. Nothing here paraphrases
a test -- if a description is wrong, the docstring is wrong, and both are in the same review.

Parametrised cases are folded back into their test function: `test_energy_matches_upstream` ran
eight times, and eight rows of near-identical ids would bury the thirty things the suite actually
checks.

    python -m squidpy_ports.stalign.test_report \
        --suite "this repo:tests/test_stalign.py:ports.xml" \
        --suite "squidpy fork:../squidpy/tests/.../test_align.py:fork.xml" \
        --output docs/tests/results.md
"""

from __future__ import annotations

import argparse
import ast
import xml.etree.ElementTree as ET
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

#: JUnit records an xfail as `<skipped type="pytest.xfail">`, which is indistinguishable from a
#: real skip on the tag alone. The type attribute is the only thing that separates "we expect this
#: to fail and pinned why" from "this did not run".
_XFAIL_TYPE = "pytest.xfail"


@dataclass
class TestFunction:
    """One test function, with every parametrised case it expanded into folded back in."""

    name: str
    doc: str = ""
    outcomes: Counter[str] = field(default_factory=Counter)
    #: xfail/skip reasons, deduplicated -- parametrised cases usually repeat one reason.
    reasons: list[str] = field(default_factory=list)

    @property
    def cases(self) -> int:
        """How many parametrised cases this function expanded into."""
        return sum(self.outcomes.values())

    @property
    def status(self) -> str:
        """Worst outcome, so a table can never show `passed` for a function that failed once."""
        for outcome in ("failed", "error", "skipped", "xfailed", "passed"):
            if self.outcomes[outcome]:
                return outcome
        return "not run"


def _docstrings(source: Path) -> dict[str, str]:
    """First docstring line of every `test_*` function in `source`, keyed by name."""
    tree = ast.parse(source.read_text())
    return {
        node.name: (ast.get_docstring(node) or "").strip().split("\n")[0]
        for node in ast.walk(tree)
        if isinstance(node, ast.FunctionDef) and node.name.startswith("test_")
    }


def _outcome(case: ET.Element) -> tuple[str, str]:
    """Map one `<testcase>` onto an outcome and the reason pytest recorded for it."""
    for child in case:
        if child.tag in ("failure", "error"):
            return ("failed" if child.tag == "failure" else "error", child.get("message", ""))
        if child.tag == "skipped":
            kind = "xfailed" if child.get("type") == _XFAIL_TYPE else "skipped"
            return kind, child.get("message", "")
    return "passed", ""


def collect(junit: Path, source: Path) -> list[TestFunction]:
    """Fold a JUnit report and its test source into one ordered list of test functions.

    Order follows the source file, not the report: the suites are written layer by layer
    (primitives, then energy, then the loop), and that ordering is the only grouping the page has.
    """
    docs = _docstrings(source)
    functions: dict[str, TestFunction] = {name: TestFunction(name, doc) for name, doc in docs.items()}

    root = ET.parse(junit).getroot()
    for case in root.iter("testcase"):
        # `test_energy_matches_upstream[v_zero-False-1]` -> `test_energy_matches_upstream`
        name = (case.get("name") or "").split("[")[0]
        if name not in functions:
            continue  # a different file in the same report
        outcome, reason = _outcome(case)
        function = functions[name]
        function.outcomes[outcome] += 1
        if reason and reason not in function.reasons:
            function.reasons.append(reason)

    return [f for f in functions.values() if f.cases]


_BADGE = {
    "passed": "pass",
    "xfailed": "expected failure",
    "skipped": "skipped",
    "failed": "**FAIL**",
    "error": "**ERROR**",
}


def render(suites: list[tuple[str, Path, list[TestFunction]]]) -> str:
    """Render the summary table, the non-passing detail, and a table per suite."""
    lines: list[str] = []
    totals: Counter[str] = Counter()
    for _, _, functions in suites:
        for function in functions:
            totals.update(function.outcomes)

    lines += ["<!-- Generated by squidpy_ports.stalign.test_report. Do not edit by hand. -->", ""]
    lines += ["| Suite | Test functions | Cases | Result |", "| --- | --- | --- | --- |"]
    for label, source, functions in suites:
        counts = Counter()
        for function in functions:
            counts.update(function.outcomes)
        result = ", ".join(f"{n} {name}" for name, n in sorted(counts.items()))
        lines.append(f"| `{source.name}` | {label} | {len(functions)} | {sum(counts.values())} cases: {result} |")
    lines += [""]

    failed = totals["failed"] + totals["error"]
    verdict = f"**{failed} failing**" if failed else "**No failures.**"
    lines += [
        f"{verdict} {totals['passed']} passing cases, {totals['xfailed']} expected failures, "
        f"{totals['skipped']} skipped, across {sum(len(f) for _, _, f in suites)} test functions.",
        "",
    ]

    notable = [(label, f) for label, _, functions in suites for f in functions if f.status != "passed"]
    if notable:
        lines += [
            "### Everything that did not simply pass",
            "",
            "| Test | Outcome | Reason pytest recorded |",
            "| --- | --- | --- |",
        ]
        for label, function in notable:
            reason = " ".join(function.reasons).replace("|", "\\|").replace("\n", " ")
            lines.append(f"| `{function.name}` <br><sub>{label}</sub> | {_BADGE[function.status]} | {reason or '—'} |")
        lines += [""]

    for label, source, functions in suites:
        lines += [
            f"### `{source.name}` — {label}",
            "",
            "| Test | Asserts | Cases | Result |",
            "| --- | --- | --- | --- |",
        ]
        for function in functions:
            doc = function.doc.replace("|", "\\|") or "—"
            lines.append(f"| `{function.name}` | {doc} | {function.cases} | {_BADGE[function.status]} |")
        lines += [""]

    # rstrip first: each section appends a trailing "", and a file ending in a blank line is
    # what end-of-file-fixer would rewrite -- CI commits this without running the hooks.
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> None:
    """Stalign"""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--suite",
        action="append",
        required=True,
        metavar="LABEL:SOURCE:JUNIT",
        help="colon-separated label, test source file, and the JUnit XML reporting it",
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    suites = []
    for spec in args.suite:
        label, source, junit = spec.rsplit(":", 2)
        suites.append((label, Path(source), collect(Path(junit), Path(source))))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(suites))
    print(f"wrote {args.output} from {len(suites)} suite(s)")


if __name__ == "__main__":
    main()
